#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteca.API
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BibliotecaDB")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCategoria(Categoria instance);
    partial void UpdateCategoria(Categoria instance);
    partial void DeleteCategoria(Categoria instance);
    partial void InsertLivro(Livro instance);
    partial void UpdateLivro(Livro instance);
    partial void DeleteLivro(Livro instance);
    partial void InsertUtilizador(Utilizador instance);
    partial void UpdateUtilizador(Utilizador instance);
    partial void DeleteUtilizador(Utilizador instance);
    partial void InsertEmprestimo(Emprestimo instance);
    partial void UpdateEmprestimo(Emprestimo instance);
    partial void DeleteEmprestimo(Emprestimo instance);
    #endregion
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Categoria> Categorias
		{
			get
			{
				return this.GetTable<Categoria>();
			}
		}
		
		public System.Data.Linq.Table<Livro> Livros
		{
			get
			{
				return this.GetTable<Livro>();
			}
		}
		
		public System.Data.Linq.Table<Utilizador> Utilizadors
		{
			get
			{
				return this.GetTable<Utilizador>();
			}
		}
		
		public System.Data.Linq.Table<Emprestimo> Emprestimos
		{
			get
			{
				return this.GetTable<Emprestimo>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Categorias")]
	public partial class Categoria : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdCategoria;
		
		private string _Nome;
		
		private string _Descricao;
		
		private EntitySet<Livro> _Livros;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdCategoriaChanging(int value);
    partial void OnIdCategoriaChanged();
    partial void OnNomeChanging(string value);
    partial void OnNomeChanged();
    partial void OnDescricaoChanging(string value);
    partial void OnDescricaoChanged();
    #endregion
		
		public Categoria()
		{
			this._Livros = new EntitySet<Livro>(new Action<Livro>(this.attach_Livros), new Action<Livro>(this.detach_Livros));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCategoria", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdCategoria
		{
			get
			{
				return this._IdCategoria;
			}
			set
			{
				if ((this._IdCategoria != value))
				{
					this.OnIdCategoriaChanging(value);
					this.SendPropertyChanging();
					this._IdCategoria = value;
					this.SendPropertyChanged("IdCategoria");
					this.OnIdCategoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this.OnNomeChanging(value);
					this.SendPropertyChanging();
					this._Nome = value;
					this.SendPropertyChanged("Nome");
					this.OnNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descricao", DbType="NVarChar(150)")]
		public string Descricao
		{
			get
			{
				return this._Descricao;
			}
			set
			{
				if ((this._Descricao != value))
				{
					this.OnDescricaoChanging(value);
					this.SendPropertyChanging();
					this._Descricao = value;
					this.SendPropertyChanged("Descricao");
					this.OnDescricaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Categoria_Livro", Storage="_Livros", ThisKey="IdCategoria", OtherKey="IdCategoria")]
		public EntitySet<Livro> Livros
		{
			get
			{
				return this._Livros;
			}
			set
			{
				this._Livros.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Livros(Livro entity)
		{
			this.SendPropertyChanging();
			entity.Categoria = this;
		}
		
		private void detach_Livros(Livro entity)
		{
			this.SendPropertyChanging();
			entity.Categoria = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Livros")]
	public partial class Livro : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdLivro;
		
		private string _CodigoLivro;
		
		private string _Titulo;
		
		private string _Autor;
		
		private string _Editora;
		
		private int _AnoPublicacao;
		
		private string _Genero;
		
		private int _ExemplaresDisponiveis;
		
		private int _IdCategoria;
		
		private EntitySet<Emprestimo> _Emprestimos;
		
		private EntityRef<Categoria> _Categoria;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdLivroChanging(int value);
    partial void OnIdLivroChanged();
    partial void OnCodigoLivroChanging(string value);
    partial void OnCodigoLivroChanged();
    partial void OnTituloChanging(string value);
    partial void OnTituloChanged();
    partial void OnAutorChanging(string value);
    partial void OnAutorChanged();
    partial void OnEditoraChanging(string value);
    partial void OnEditoraChanged();
    partial void OnAnoPublicacaoChanging(int value);
    partial void OnAnoPublicacaoChanged();
    partial void OnGeneroChanging(string value);
    partial void OnGeneroChanged();
    partial void OnExemplaresDisponiveisChanging(int value);
    partial void OnExemplaresDisponiveisChanged();
    partial void OnIdCategoriaChanging(int value);
    partial void OnIdCategoriaChanged();
    #endregion
		
		public Livro()
		{
			this._Emprestimos = new EntitySet<Emprestimo>(new Action<Emprestimo>(this.attach_Emprestimos), new Action<Emprestimo>(this.detach_Emprestimos));
			this._Categoria = default(EntityRef<Categoria>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdLivro", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdLivro
		{
			get
			{
				return this._IdLivro;
			}
			set
			{
				if ((this._IdLivro != value))
				{
					this.OnIdLivroChanging(value);
					this.SendPropertyChanging();
					this._IdLivro = value;
					this.SendPropertyChanged("IdLivro");
					this.OnIdLivroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoLivro", DbType="NVarChar(20)")]
		public string CodigoLivro
		{
			get
			{
				return this._CodigoLivro;
			}
			set
			{
				if ((this._CodigoLivro != value))
				{
					this.OnCodigoLivroChanging(value);
					this.SendPropertyChanging();
					this._CodigoLivro = value;
					this.SendPropertyChanged("CodigoLivro");
					this.OnCodigoLivroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Titulo", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Titulo
		{
			get
			{
				return this._Titulo;
			}
			set
			{
				if ((this._Titulo != value))
				{
					this.OnTituloChanging(value);
					this.SendPropertyChanging();
					this._Titulo = value;
					this.SendPropertyChanged("Titulo");
					this.OnTituloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Autor", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Autor
		{
			get
			{
				return this._Autor;
			}
			set
			{
				if ((this._Autor != value))
				{
					this.OnAutorChanging(value);
					this.SendPropertyChanging();
					this._Autor = value;
					this.SendPropertyChanged("Autor");
					this.OnAutorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Editora", DbType="NVarChar(100)")]
		public string Editora
		{
			get
			{
				return this._Editora;
			}
			set
			{
				if ((this._Editora != value))
				{
					this.OnEditoraChanging(value);
					this.SendPropertyChanging();
					this._Editora = value;
					this.SendPropertyChanged("Editora");
					this.OnEditoraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnoPublicacao", DbType="Int NOT NULL")]
		public int AnoPublicacao
		{
			get
			{
				return this._AnoPublicacao;
			}
			set
			{
				if ((this._AnoPublicacao != value))
				{
					this.OnAnoPublicacaoChanging(value);
					this.SendPropertyChanging();
					this._AnoPublicacao = value;
					this.SendPropertyChanged("AnoPublicacao");
					this.OnAnoPublicacaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Genero", DbType="NVarChar(50)")]
		public string Genero
		{
			get
			{
				return this._Genero;
			}
			set
			{
				if ((this._Genero != value))
				{
					this.OnGeneroChanging(value);
					this.SendPropertyChanging();
					this._Genero = value;
					this.SendPropertyChanged("Genero");
					this.OnGeneroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExemplaresDisponiveis", DbType="Int NOT NULL")]
		public int ExemplaresDisponiveis
		{
			get
			{
				return this._ExemplaresDisponiveis;
			}
			set
			{
				if ((this._ExemplaresDisponiveis != value))
				{
					this.OnExemplaresDisponiveisChanging(value);
					this.SendPropertyChanging();
					this._ExemplaresDisponiveis = value;
					this.SendPropertyChanged("ExemplaresDisponiveis");
					this.OnExemplaresDisponiveisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCategoria", DbType="Int NOT NULL")]
		public int IdCategoria
		{
			get
			{
				return this._IdCategoria;
			}
			set
			{
				if ((this._IdCategoria != value))
				{
					if (this._Categoria.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdCategoriaChanging(value);
					this.SendPropertyChanging();
					this._IdCategoria = value;
					this.SendPropertyChanged("IdCategoria");
					this.OnIdCategoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Livro_Emprestimo", Storage="_Emprestimos", ThisKey="IdLivro", OtherKey="IdLivro")]
		public EntitySet<Emprestimo> Emprestimos
		{
			get
			{
				return this._Emprestimos;
			}
			set
			{
				this._Emprestimos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Categoria_Livro", Storage="_Categoria", ThisKey="IdCategoria", OtherKey="IdCategoria", IsForeignKey=true)]
		public Categoria Categoria
		{
			get
			{
				return this._Categoria.Entity;
			}
			set
			{
				Categoria previousValue = this._Categoria.Entity;
				if (((previousValue != value) 
							|| (this._Categoria.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Categoria.Entity = null;
						previousValue.Livros.Remove(this);
					}
					this._Categoria.Entity = value;
					if ((value != null))
					{
						value.Livros.Add(this);
						this._IdCategoria = value.IdCategoria;
					}
					else
					{
						this._IdCategoria = default(int);
					}
					this.SendPropertyChanged("Categoria");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Emprestimos(Emprestimo entity)
		{
			this.SendPropertyChanging();
			entity.Livro = this;
		}
		
		private void detach_Emprestimos(Emprestimo entity)
		{
			this.SendPropertyChanging();
			entity.Livro = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Utilizadores")]
	public partial class Utilizador : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdUtilizador;
		
		private string _Nome;
		
		private string _Contacto;
		
		private string _Email;
		
		private string _TipoUtilizador;
		
		private int _LimiteEmprestimos;
		
		private int _Atrasos;
		
		private EntitySet<Emprestimo> _Emprestimos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdUtilizadorChanging(int value);
    partial void OnIdUtilizadorChanged();
    partial void OnNomeChanging(string value);
    partial void OnNomeChanged();
    partial void OnContactoChanging(string value);
    partial void OnContactoChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnTipoUtilizadorChanging(string value);
    partial void OnTipoUtilizadorChanged();
    partial void OnLimiteEmprestimosChanging(int value);
    partial void OnLimiteEmprestimosChanged();
    partial void OnAtrasosChanging(int value);
    partial void OnAtrasosChanged();
    #endregion
		
		public Utilizador()
		{
			this._Emprestimos = new EntitySet<Emprestimo>(new Action<Emprestimo>(this.attach_Emprestimos), new Action<Emprestimo>(this.detach_Emprestimos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUtilizador", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdUtilizador
		{
			get
			{
				return this._IdUtilizador;
			}
			set
			{
				if ((this._IdUtilizador != value))
				{
					this.OnIdUtilizadorChanging(value);
					this.SendPropertyChanging();
					this._IdUtilizador = value;
					this.SendPropertyChanged("IdUtilizador");
					this.OnIdUtilizadorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this.OnNomeChanging(value);
					this.SendPropertyChanging();
					this._Nome = value;
					this.SendPropertyChanged("Nome");
					this.OnNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contacto", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string Contacto
		{
			get
			{
				return this._Contacto;
			}
			set
			{
				if ((this._Contacto != value))
				{
					this.OnContactoChanging(value);
					this.SendPropertyChanging();
					this._Contacto = value;
					this.SendPropertyChanged("Contacto");
					this.OnContactoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoUtilizador", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TipoUtilizador
		{
			get
			{
				return this._TipoUtilizador;
			}
			set
			{
				if ((this._TipoUtilizador != value))
				{
					this.OnTipoUtilizadorChanging(value);
					this.SendPropertyChanging();
					this._TipoUtilizador = value;
					this.SendPropertyChanged("TipoUtilizador");
					this.OnTipoUtilizadorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LimiteEmprestimos", DbType="Int NOT NULL")]
		public int LimiteEmprestimos
		{
			get
			{
				return this._LimiteEmprestimos;
			}
			set
			{
				if ((this._LimiteEmprestimos != value))
				{
					this.OnLimiteEmprestimosChanging(value);
					this.SendPropertyChanging();
					this._LimiteEmprestimos = value;
					this.SendPropertyChanged("LimiteEmprestimos");
					this.OnLimiteEmprestimosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Atrasos", DbType="Int NOT NULL")]
		public int Atrasos
		{
			get
			{
				return this._Atrasos;
			}
			set
			{
				if ((this._Atrasos != value))
				{
					this.OnAtrasosChanging(value);
					this.SendPropertyChanging();
					this._Atrasos = value;
					this.SendPropertyChanged("Atrasos");
					this.OnAtrasosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Utilizador_Emprestimo", Storage="_Emprestimos", ThisKey="IdUtilizador", OtherKey="IdUtilizador")]
		public EntitySet<Emprestimo> Emprestimos
		{
			get
			{
				return this._Emprestimos;
			}
			set
			{
				this._Emprestimos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Emprestimos(Emprestimo entity)
		{
			this.SendPropertyChanging();
			entity.Utilizador = this;
		}
		
		private void detach_Emprestimos(Emprestimo entity)
		{
			this.SendPropertyChanging();
			entity.Utilizador = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Emprestimos")]
	public partial class Emprestimo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdEmprestimo;
		
		private int _IdUtilizador;
		
		private int _IdLivro;
		
		private System.DateTime _DataEmprestimo;
		
		private System.DateTime _PrazoDevolucao;
		
		private System.Nullable<System.DateTime> _DataDevolucao;
		
		private bool _Devolvido;
		
		private decimal _Multa;
		
		private EntityRef<Livro> _Livro;
		
		private EntityRef<Utilizador> _Utilizador;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdEmprestimoChanging(int value);
    partial void OnIdEmprestimoChanged();
    partial void OnIdUtilizadorChanging(int value);
    partial void OnIdUtilizadorChanged();
    partial void OnIdLivroChanging(int value);
    partial void OnIdLivroChanged();
    partial void OnDataEmprestimoChanging(System.DateTime value);
    partial void OnDataEmprestimoChanged();
    partial void OnPrazoDevolucaoChanging(System.DateTime value);
    partial void OnPrazoDevolucaoChanged();
    partial void OnDataDevolucaoChanging(System.Nullable<System.DateTime> value);
    partial void OnDataDevolucaoChanged();
    partial void OnDevolvidoChanging(bool value);
    partial void OnDevolvidoChanged();
    partial void OnMultaChanging(decimal value);
    partial void OnMultaChanged();
    #endregion
		
		public Emprestimo()
		{
			this._Livro = default(EntityRef<Livro>);
			this._Utilizador = default(EntityRef<Utilizador>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdEmprestimo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdEmprestimo
		{
			get
			{
				return this._IdEmprestimo;
			}
			set
			{
				if ((this._IdEmprestimo != value))
				{
					this.OnIdEmprestimoChanging(value);
					this.SendPropertyChanging();
					this._IdEmprestimo = value;
					this.SendPropertyChanged("IdEmprestimo");
					this.OnIdEmprestimoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUtilizador", DbType="Int NOT NULL")]
		public int IdUtilizador
		{
			get
			{
				return this._IdUtilizador;
			}
			set
			{
				if ((this._IdUtilizador != value))
				{
					if (this._Utilizador.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdUtilizadorChanging(value);
					this.SendPropertyChanging();
					this._IdUtilizador = value;
					this.SendPropertyChanged("IdUtilizador");
					this.OnIdUtilizadorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdLivro", DbType="Int NOT NULL")]
		public int IdLivro
		{
			get
			{
				return this._IdLivro;
			}
			set
			{
				if ((this._IdLivro != value))
				{
					if (this._Livro.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdLivroChanging(value);
					this.SendPropertyChanging();
					this._IdLivro = value;
					this.SendPropertyChanged("IdLivro");
					this.OnIdLivroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataEmprestimo", DbType="DateTime NOT NULL")]
		public System.DateTime DataEmprestimo
		{
			get
			{
				return this._DataEmprestimo;
			}
			set
			{
				if ((this._DataEmprestimo != value))
				{
					this.OnDataEmprestimoChanging(value);
					this.SendPropertyChanging();
					this._DataEmprestimo = value;
					this.SendPropertyChanged("DataEmprestimo");
					this.OnDataEmprestimoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrazoDevolucao", DbType="DateTime NOT NULL")]
		public System.DateTime PrazoDevolucao
		{
			get
			{
				return this._PrazoDevolucao;
			}
			set
			{
				if ((this._PrazoDevolucao != value))
				{
					this.OnPrazoDevolucaoChanging(value);
					this.SendPropertyChanging();
					this._PrazoDevolucao = value;
					this.SendPropertyChanged("PrazoDevolucao");
					this.OnPrazoDevolucaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataDevolucao", DbType="DateTime")]
		public System.Nullable<System.DateTime> DataDevolucao
		{
			get
			{
				return this._DataDevolucao;
			}
			set
			{
				if ((this._DataDevolucao != value))
				{
					this.OnDataDevolucaoChanging(value);
					this.SendPropertyChanging();
					this._DataDevolucao = value;
					this.SendPropertyChanged("DataDevolucao");
					this.OnDataDevolucaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Devolvido", DbType="Bit NOT NULL")]
		public bool Devolvido
		{
			get
			{
				return this._Devolvido;
			}
			set
			{
				if ((this._Devolvido != value))
				{
					this.OnDevolvidoChanging(value);
					this.SendPropertyChanging();
					this._Devolvido = value;
					this.SendPropertyChanged("Devolvido");
					this.OnDevolvidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Multa", DbType="Decimal(10,2) NOT NULL")]
		public decimal Multa
		{
			get
			{
				return this._Multa;
			}
			set
			{
				if ((this._Multa != value))
				{
					this.OnMultaChanging(value);
					this.SendPropertyChanging();
					this._Multa = value;
					this.SendPropertyChanged("Multa");
					this.OnMultaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Livro_Emprestimo", Storage="_Livro", ThisKey="IdLivro", OtherKey="IdLivro", IsForeignKey=true)]
		public Livro Livro
		{
			get
			{
				return this._Livro.Entity;
			}
			set
			{
				Livro previousValue = this._Livro.Entity;
				if (((previousValue != value) 
							|| (this._Livro.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Livro.Entity = null;
						previousValue.Emprestimos.Remove(this);
					}
					this._Livro.Entity = value;
					if ((value != null))
					{
						value.Emprestimos.Add(this);
						this._IdLivro = value.IdLivro;
					}
					else
					{
						this._IdLivro = default(int);
					}
					this.SendPropertyChanged("Livro");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Utilizador_Emprestimo", Storage="_Utilizador", ThisKey="IdUtilizador", OtherKey="IdUtilizador", IsForeignKey=true)]
		public Utilizador Utilizador
		{
			get
			{
				return this._Utilizador.Entity;
			}
			set
			{
				Utilizador previousValue = this._Utilizador.Entity;
				if (((previousValue != value) 
							|| (this._Utilizador.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Utilizador.Entity = null;
						previousValue.Emprestimos.Remove(this);
					}
					this._Utilizador.Entity = value;
					if ((value != null))
					{
						value.Emprestimos.Add(this);
						this._IdUtilizador = value.IdUtilizador;
					}
					else
					{
						this._IdUtilizador = default(int);
					}
					this.SendPropertyChanged("Utilizador");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
