<?xml version="1.0" encoding="utf-8"?><Database Name="BibliotecaDB" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.Categorias" Member="Categorias">
    <Type Name="Categoria">
      <Column Name="IdCategoria" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nome" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Descricao" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Association Name="Categoria_Livro" Member="Livros" ThisKey="IdCategoria" OtherKey="IdCategoria" Type="Livro" />
    </Type>
  </Table>
  <Table Name="dbo.Livros" Member="Livros">
    <Type Name="Livro">
      <Column Name="IdLivro" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CodigoLivro" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Titulo" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Autor" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Editora" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="AnoPublicacao" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Genero" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ExemplaresDisponiveis" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdCategoria" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Livro_Emprestimo" Member="Emprestimos" ThisKey="IdLivro" OtherKey="IdLivro" Type="Emprestimo" />
      <Association Name="Livro_Reserva" Member="Reservas" ThisKey="IdLivro" OtherKey="IdLivro" Type="Reserva" />
      <Association Name="Categoria_Livro" Member="Categoria" ThisKey="IdCategoria" OtherKey="IdCategoria" Type="Categoria" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Utilizadores" Member="Utilizadors">
    <Type Name="Utilizador">
      <Column Name="IdUtilizador" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nome" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Contacto" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="TipoUtilizador" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LimiteEmprestimos" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Atrasos" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Utilizador_Emprestimo" Member="Emprestimos" ThisKey="IdUtilizador" OtherKey="IdUtilizador" Type="Emprestimo" />
      <Association Name="Utilizador_Penalizacoes" Member="Penalizacoes" Storage="_Penalizacaos" ThisKey="IdUtilizador" OtherKey="IdUtilizador" Type="Penalizacoes" />
      <Association Name="Utilizador_Reserva" Member="Reservas" ThisKey="IdUtilizador" OtherKey="IdUtilizador" Type="Reserva" />
    </Type>
  </Table>
  <Table Name="dbo.Emprestimos" Member="Emprestimos">
    <Type Name="Emprestimo">
      <Column Name="IdEmprestimo" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdUtilizador" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdLivro" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DataEmprestimo" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="PrazoDevolucao" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DataDevolucao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Devolvido" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Multa" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Association Name="Emprestimo_Penalizacoes" Member="Penalizacoes" Storage="_Penalizacaos" ThisKey="IdEmprestimo" OtherKey="IdEmprestimo" Type="Penalizacoes" />
      <Association Name="Livro_Emprestimo" Member="Livro" ThisKey="IdLivro" OtherKey="IdLivro" Type="Livro" IsForeignKey="true" />
      <Association Name="Utilizador_Emprestimo" Member="Utilizador" ThisKey="IdUtilizador" OtherKey="IdUtilizador" Type="Utilizador" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Penalizacoes" Member="Penalizacoes">
    <Type Name="Penalizacoes">
      <Column Name="IdPenalizacao" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdUtilizador" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdEmprestimo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Valor" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="DiasAtraso" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Motivo" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="DataPenalizacao" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Pago" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DataPagamento" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Emprestimo_Penalizacoes" Member="Emprestimo" ThisKey="IdEmprestimo" OtherKey="IdEmprestimo" Type="Emprestimo" IsForeignKey="true" DeleteRule="SET NULL" />
      <Association Name="Utilizador_Penalizacoes" Member="Utilizador" ThisKey="IdUtilizador" OtherKey="IdUtilizador" Type="Utilizador" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Reservas" Member="Reservas">
    <Type Name="Reserva">
      <Column Name="IdReserva" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdUtilizador" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdLivro" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DataReserva" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Ordem" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Ativa" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DataDisponivel" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Livro_Reserva" Member="Livro" ThisKey="IdLivro" OtherKey="IdLivro" Type="Livro" IsForeignKey="true" />
      <Association Name="Utilizador_Reserva" Member="Utilizador" ThisKey="IdUtilizador" OtherKey="IdUtilizador" Type="Utilizador" IsForeignKey="true" />
    </Type>
  </Table>
</Database>