<?xml version="1.0" encoding="utf-8"?><Database Name="BibliotecaDB" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.Categorias" Member="Categorias">
    <Type Name="Categoria">
      <Column Name="IdCategoria" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nome" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Descricao" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Association Name="Categoria_Livro" Member="Livros" ThisKey="IdCategoria" OtherKey="IdCategoria" Type="Livro" />
    </Type>
  </Table>
  <Table Name="dbo.Livros" Member="Livros">
    <Type Name="Livro">
      <Column Name="IdLivro" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CodigoLivro" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Titulo" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Autor" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Editora" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="AnoPublicacao" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Genero" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ExemplaresDisponiveis" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdCategoria" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Categoria_Livro" Member="Categoria" ThisKey="IdCategoria" OtherKey="IdCategoria" Type="Categoria" IsForeignKey="true" />
    </Type>
  </Table>
</Database>